### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by brennanerbz** [aidangomez/weblm#8]
Tried this objective: "buy me slippers on Amazon"

Received this error:

```
Traceback (most recent call last):
  File "/Users/brennanerbz/miniconda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/brennanerbz/miniconda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/brennanerbz/Desktop/AI/weblm/weblm/main.py", line 65, in <module>
    response = controller.step(crawler.page.url, content, response)
  File "/Users/brennanerbz/Desktop/AI/weblm/weblm/controller.py", line 673, in step
    action_or_prompt = self.pick_action(url, page_elements, response)
  File "/Users/brennanerbz/Desktop/AI/weblm/weblm/controller.py", line 508, in pick_action
    state, prompt = self._shorten_prompt(url, elements, examples, target=MAX_SEQ_LEN)
  File "/Users/brennanerbz/Desktop/AI/weblm/weblm/controller.py", line 429, in _shorten_prompt
    tokens = tokenized_prompt.token_strings
  File "/Users/brennanerbz/Library/Caches/pypoetry/virtualenvs/weblm-2wztWxgM-py3.9/lib/python3.9/site-packages/cohere/response.py", line 36, in __getattribute__
    return attr.resolve()
  File "/Users/brennanerbz/Library/Caches/pypoetry/virtualenvs/weblm-2wztWxgM-py3.9/lib/python3.9/site-packages/cohere/response.py", line 28, in resolve
    return self._getter(self._request.result())
  File "/Users/brennanerbz/miniconda/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/brennanerbz/miniconda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/brennanerbz/miniconda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/brennanerbz/Library/Caches/pypoetry/virtualenvs/weblm-2wztWxgM-py3.9/lib/python3.9/site-packages/cohere/client.py", line 260, in __request
    raise CohereError(message=response.text, http_status=response.status_code, headers=response.headers)
cohere.error.CohereError: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```

**Comment by brennanerbz** [comment]
@aidangomez any suggestions?
